### ISSUE TITLE
Anusuiya comments via email

### ISSUE THREAD

**Issue by markziemann** [markziemann/5pillars#10]
1. I am not sure if this is relevant but recently, in one of our modules, we were asked to perform analysis of metagenomic papers. We were asked to use similar bioinformatics tools in the Galaxy server compared to the tools that were used as stand-alone options by the researchers originally. I used the same tools that were present in galaxy (for example - Kraken2 - for taxonomical classification - an updated version of kraken1). The results were not very similar, even though taxonomical classification was done through Kraken2 and the stand-alone tools (like Kraken1). This can also mean that the results of Kraken1 used by researchers earlier can be problematic or may no longer be valid?

2. Also, the authors did not mention some statistical criteria and the base database to compare the datasets with. These were important information to analyse the datasets, and hence, we went in with the default settings. Even though stand-alone tools were used by the authors, I was able to perform similar processes using different tools in Galaxy - still, the results were very different. Again, this raises the importance of proper documentation.

3. I understand that different tools cannot give the exact same results, but they should be able to give a similar idea/picture of the results right (as taxonomical classification was the ultimate goal), plus Kraken 2 is just an updated version of kraken1. I was just wondering if it would be too much to expect for similar bioinformatics tools to produce similar - if not the exact results? 

4. Another point in documentation or "FAIR" can be that - most of the papers do not label the supplementary files properly, and sometimes, even in the CSV file contents, there are no mentions of what the results in the Excel sheet are about. There was also a metagenomic study with 40+ datasets and none of the datasets were labelled with an identifier that can be used to identify that dataset in the manuscript. Anonymity can still be maintained with patient samples, however, not labelling properly makes it difficult to reproduce the results sometimes. I had to discard that paper altogether as the option of reproducibility was not at all possible. I had similar issues with supplementary files and finding relevant results during my bachelor's project as well...

**Comment by markziemann** [comment]
1. This is interesting - is there a reference we can cite in the MS describing discordant kraken1/2 results? Was the command and software version in Galaxy exactly the same as the command line? Sometimes the galaxy packages are not updated as quickly as the standard tools.
2. Yes this is an important. We can add an example like this to to line 554  of the MS which discusses the importance of methodological reporting.
3. Sometimes the version changes cause quite dramatic changes to results. I'm sure authors expect the results to be similar in the updated versions, but their biggest motivation is towards improvement in overall accracy, so this means that some users might experience big shifts in results between versions. In those cases the new version should give the more accurate results even though it appears that the v1 and v2 results don't agree much.
4. I tried to recommend against the use of supplementary files. But you are correct in that the data files are not described that well, for example what the columns mean. It is up to the data authors to describe this in detail. I will add a bullet point to recommendations in FAIR data section outlining this. As you rightly indicate, the metadata is equally critical as the data itself. Sometimes data are shared on NCBI/GEO but without the metadata so we can't figure out which are the control and disease groups. I will see if I can find an example and then include a quick description in the MS text.

**Comment by anusuiyaxbora** [comment]
1. I could not get particular references that report that kraken1/2 gives different results. According to my analysis, it appeared that way. It seems to be that Kraken2 is updated in Galaxy... Kraken2 was officially released in 2018 and is available on Galaxy since April 2019. 
3. According to the developer's website, "Kraken2 has significant memory and speed improvements while maintaining the original Kraken classification algorithm and k-mer based classification." (Here Kraken = Kraken1) In this case, probably the results should have been a bit similar if Kraken 2 is mostly better due to less usage of memory (RAM).

**Comment by markziemann** [comment]
Great I think I have covered these points. Please reopen if you think I missed something.
