### ISSUE TITLE
Make parallel with the 3 pillars of open science?

### ISSUE THREAD

**Issue by pierrepo** [markziemann/5pillars#11]
We often say that open science is based on 3 pillars (see for instance https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1002506 figure 1):

1. **open data**
2. **open source** software
3. **open access** to publications

I guess we could make a parallel between these 3 pillars and the 5 for reproducibility from this work:

- **open data** -> FAIR & persistent data sharing
- **open source** -> Code version control & sharing
- **open access** -> Documentation

Are the extra 2 (Comput env control & Literate programming) the gist of reproducibility? Making your code explicitely work the same for the former, and making clear connection between code and data for the latter.

**Comment by markziemann** [comment]
Yes - this is worth mentioning. I have made some light modifications to the text:

>A number of guides recommending enhanced computational reproducibility practices have been developed
> [ @Tan2010-is; @Peng2011-ia; @Sandve2013-lk; @Piccolo2016-ji; @Lewis2016-qh;
> @Wilson2017-uq ; @Akalin2018-eg ; @Gruning2018-sg; @Brito2020-ld; @Peikert2021-eq ; @Rodrigues2023-fw;
> @DuPre2022-bk].
> Inspired by these principles and the three pillars of open science framework, (open data, code
> and papers) [@Gorgolewski2016-hv], this article presents the
> *five pillars of reproducible computational research* (**Figure 1**).
> The intended audience is bioinformatics data analysts (not tool developers), however the
> principles described here could equally apply to other domains of study.

If you can think of a better way to explain, I'd be grateful!

**Comment by markziemann** [comment]
Have elaborated a bit more:

>A number of guides recommending enhanced computational reproducibility practices have been developed [10–21]. >Inspired by these principles, this article presents the five pillars of reproducible computational research (Figure 1). >There are clear parallels with the established the three pillars of open science framework, (open data, code and papers) >[22]. Here, the emphasis is on practical reproducibility with an increased focus on programming practices, transparent >reporting and the role of computational environments. The intended audience is bioinformatics data analysts (not tool >developers), however the principles described here could equally apply to other domains of study.

>22. Gorgolewski KJ, Poldrack RA. A practical guide for improving transparency and reproducibility in neuroimaging research. PLoS Biol. 2016; 14:e1002506

Let me know if you think this is sufficient.

**Comment by pierrepo** [comment]
No need to go further, I guess. This is very nice.
