### ISSUE TITLE
Software archiving

### ISSUE THREAD

**Issue by pierrepo** [markziemann/5pillars#13]
Regarding Software archiving:

> Zenodo and Software Heritage repositories are both good options for long-term archiving of software, and the link to these should be provided in the respective journal article/pre-print.

I would tend to push toward Software Heritage only -- or a least make a clear distinction between the 2 solutions -- since Zenodo (nor Figshare) have been designed for software archiving.

Software Heritage mission is to collect and archive source code (and source code only). It retains the full history of the project and ease the citation of the software archived by providing an [intrinsic identifier](https://www.softwareheritage.org/2020/07/09/intrinsic-vs-extrinsic-identifiers/) called the SWHID.

I can make a PR for this if you agree.

**Comment by markziemann** [comment]
Yes please!

**Comment by markziemann** [comment]
Thanks - looks great!
