### ISSUE TITLE
Practical guides

### ISSUE THREAD

**Issue by markziemann** [markziemann/5pillars#15]
https://github.com/markziemann/5pillars/blob/41bb93e261a92a6c518cfdd82f3e2246cac1669b/guides/practical_guides.Rmd#LL58C1-L62C18

Hi @anusuiyaxbora I'm putting together a document containing some helpful links for folks wanting to implement the 5 pillars aproach so we can point them to these resources to get started. I'm looking for tutorials, methods, videos and articles for the following:
* Intro to R and Rstudio (2-3 items)
* Intro to Python and iPython IDE (2-3 items)
* Intro to vscode (2-3 items)

**Comment by anusuiyaxbora** [comment]
Hello,
Are you looking for published books for these or will websites also work? 
1) I saw https://r4ds.had.co.nz/ this guide getting promoted on Twitter. 

2) The "Data Analysis with R Specialization" course by Duke University in Coursera can be studied, financial aid option can be used to get certified. 

Some other links are:

3) https://learningstatisticswithr.com/

4) https://bookdown.org/ndphillips/YaRrr/ (I think that this will be helpful!)

**Comment by markziemann** [comment]
Yes that's great. Websites and ebooks are perfect. I will add these to the guide. Can you also find intro to rstudio, python and vscode? Thanks

**Comment by markziemann** [comment]
Hey @anusuiyaxbora I've populated some guides in the latest commit. Could you take a look here: https://ziemann-lab.net/public/5pillars/practical_guides.html
And let me know whether you approve of these sources.

Also could you add these links to The Internet Archive? https://archive.org/web/
Submit the links to the "Save Page Now". Thanks

**Comment by anusuiyaxbora** [comment]
Yes definitely, I will check the links and will add them to the archive. Will send in new links that I think are useful for the rest of the topics!

**Comment by markziemann** [comment]
Thanks @pierrepo! These are great resources.
@anusuiyaxbora can you add these to guides/practical_guides.Rmd?

Snakemake materials go under the "end-to-end process" subheading. The ones related to git go under the git/github subheading.

Article is nearly ready to go.

**Comment by anusuiyaxbora** [comment]
Yes, I will add the new links that were suggested!

**Comment by anusuiyaxbora** [comment]
Hello @markziemann 
I have added the additional links to the Rmd file. All the links have been saved on The Internet Archive as well! 

Just some queries:
1. Can you please once check if the "Introduction to Using Git in Jupyter" (https://andgarc.github.io/basic-git-jupyter-lesson/index.html) link got repeated under the "practical guides for git and github" section... 

2. Is the 3rd link under the "Practical guides to data sharing" heading working? Maybe https://zenodo.org/record/3518692 this link would be better? 

3. Will this link be useful as part of the list of guides? "Running Basic Statistical Analysis in R" - https://www.youtube.com/watch?v=I6FJo8x1wZE
