### ISSUE TITLE
Pre-flight check

### ISSUE THREAD

**Issue by markziemann** [markziemann/5pillars#18]
Hi @pierrepo @sminot @anusuiyaxbora ,
The article is nearing completion so we need to go through some pre-flight checks. Here is the live version: https://ziemann-lab.net/public/5pillars/5pillars.html

My plan is to submit to briefings in bioinformatics, which hasn't published a best practices article like this for many years. I'll also be depositing the preprint at the same time - probably to https://osf.io/

Before I do that, there are some recent changes that I need you to check:
* Your names, affiliations and ORCID information
* The overall content
* Conclusion
* Key points (this is a requirement for BiB)
* Author biographies (this is a requirement for BiB)
* Funding: if you would like to acknowledge specific funding sources. Otherwise I will write "The authors received no specific funding for this work."
* 
If you have noticed something that needs addressing, please raise a new issue and I will manage the changes.

We will provide a supplementary file listing some recommended learning resources. Here is the link (https://ziemann-lab.net/public/5pillars/practical_guides.html). If you have any suggestions, please add them to issue #15

I'm hoping to have this round of changes completed on the ~16th June. If you approve of the manuscript please reply "approve" below. After this, I will send out the pdf version for proof reading and approval.

**Thanks for your contribution!**

**Comment by pierrepo** [comment]
@markziemann 
I've re-read the whole paper and proposed a couple of references and small additions in PR #20. 
I also double-checked the conclusion, key points and author bio.
I do not have specific funding for this work.

**Comment by pierrepo** [comment]
Also I add a quick look at Briefings in Bioinformatics [author guidelines](https://academic.oup.com/bib/pages/General_Instructions):
- I did not find any limit regarding the number of references (we should have about a hundred after PR #20)
- Reviews should be in the 2000 - 7000 words limit. We are currently at 6500 (also with PR #20).

**Comment by markziemann** [comment]
Awesome work @pierrepo these have been incorporated.
5785 words and 105 citations.

**Comment by markziemann** [comment]
There was a slight change in some of the wording and fig4 was altered to avoid possible copyright problems.

@pierrepo and @anusuiyaxbora please let me know if you approve for submission.

[5pillars.pdf](https://github.com/markziemann/5pillars/files/11724984/5pillars.pdf)
[5pillars.docx](https://github.com/markziemann/5pillars/files/11724985/5pillars.docx)

**Comment by anusuiyaxbora** [comment]
Everything looks great to me! I am fine with the affiliation, author biography and funding as well!

**Comment by markziemann** [comment]
Good suggestions.  I will fix these now.

**Comment by markziemann** [comment]
5797 words and 108 references.

@pierrepo please check those relevant sections.

[5pillars_20230613.docx](https://github.com/markziemann/5pillars/files/11735025/5pillars_20230613.docx)

[5pillars_20230613.pdf](https://github.com/markziemann/5pillars/files/11735024/5pillars_20230613.pdf)

**Comment by pierrepo** [comment]
@markziemann :pray: 

This is all good for me :tada:

**Comment by markziemann** [comment]
It has been submitted - let's see what the reviewers say
