### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by markziemann** [markziemann/5pillars#19]
https://twitter.com/Cghlewis/status/1666797320350973952?t=5a6EuHesR7y9GUzulbhM_Q&s=19

![20230609_223147.jpg](https://github.com/markziemann/5pillars/assets/5591840/cf23d76f-8a63-4fb7-951b-f3328aa7c8d1)

**Comment by pierrepo** [comment]
Also have a look to https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1000424
and 
![](https://journals.plos.org/ploscompbiol/article/figure/image?size=large&id=10.1371/journal.pcbi.1000424.g001)

**Comment by markziemann** [comment]
Thanks @pierrepo I've included your suggestion in the practical guide. 

I considered adding something to the main paper but decided against it.
