### ISSUE TITLE
Random seeds  (from Martin)

### ISSUE THREAD

**Issue by markziemann** [markziemann/5pillars#22]
They seem to be important for some workflows like community ecology (uses permutational ANOVA), and scRNA-seq analysis with UMAP and t-SNE.

**Comment by pierrepo** [comment]
You mean: fixing random seeds before performing any calculation or analysis?

**Comment by markziemann** [comment]
The BiB system bounced the manuscript back, asking for figures to all go at the end of the document [🙄](https://emojipedia.org/face-with-rolling-eyes/)

So yes, I'm thinking about including a passage in the "end-to-end process" section that addresses this.

It needs a reference to UMAP random seed and to the Sandve2013-lk reference for fixing seed as the solution.

**Comment by pierrepo** [comment]
> The BiB system bounced the manuscript back, asking for figures to all go at the end of the document

So 2000's!

I have an additional reference illustrating how to fix random seed (with examples in Python):  
https://www.frontiersin.org/articles/10.3389/fninf.2017.00069/full
> But for sequential and deterministically parallel programs (Hines, and Carnevale, 2008; Collange et al., 2015) not depending on analog inputs, it often comes down to controlling the initialization of the pseudo-random number generators (RNG). For our program, that means setting the seed of the random module.

But nothing specific to UMAP.

**Comment by markziemann** [comment]
Thanks for that - I will incorporate it and find a UMAP/t-SNE reference later today.

**Comment by markziemann** [comment]
@pierrepo do you think this addition is okay? [☝️](https://emojipedia.org/index-pointing-up/)

**Comment by pierrepo** [comment]
Sorry for the late reply @markziemann 
Maybe provide also the usual acronyms (t-SNE and UMAP) as most people know these algorithms by these names. Otherwise, this is perfect (and very well referenced)!
