### ISSUE TITLE
Need orcid IDs of authors

### ISSUE THREAD

**Issue by markziemann** [markziemann/5pillars#3]

**Comment by markziemann** [comment]
@anusuiyaxbora can you make an ORCID account? Go to  https://orcid.org/ and fill out the sign up page. It will help collect your publication information throughout your career :) Please send me your ORCID number for example mine is 0000-0002-7688-6974

**Comment by anusuiyaxbora** [comment]
Yes sure, my ORCID number is: 0009-0006-2908-1352 (https://orcid.org/0009-0006-2908-1352)

**Comment by anusuiyaxbora** [comment]
Yes sure, my ORCID number is: 0009-0006-2908-1352 (
https://orcid.org/0009-0006-2908-1352)

Kind regards,
Anusuiya
