### ISSUE TITLE
Guix build

### ISSUE THREAD

**Issue by markziemann** [markziemann/5pillars#7]
Let's give guix a try

**Comment by markziemann** [comment]
https://pubmed.ncbi.nlm.nih.gov/30277498/
https://pubmed.ncbi.nlm.nih.gov/36195618/

**Comment by pierrepo** [comment]
Also:
https://inria.hal.science/hal-03604971/en

**Comment by markziemann** [comment]
Thanks for this! I like the idea of verifiability. I have mentioned it in the latest commit.

**Comment by markziemann** [comment]
@pierrepo, here is the wording for the Guix paragraph - let us know if you approve by closing the issue.

>Guix is described as a “functional package manager” and has the unique benefit of giving bit-for-bit build reproducibility and verifiability [45,54]. This is a notable advantage, as Docker images are not verifiable nor guaranteed to build reproducibly in the future due to link decay. Moreover, Guix can build and output environments as Docker-compatible images which solves the provenance problem of such environments [55]. These features are being used in the bioinformatics sphere to create highly reproducible pipelines that work equally well on personal as well as shared high performance computers [54,56]. Guix is probably one of the best solution so far for the “ten-year challenge” of code reproducibility [57]. Although Guix has some exciting functionality, there remains a relative lack of step-by-step guides and tutorials, illustrated by the complete absence of published Guix protocols in protocols.io, as compared to 13 and 12 related to “Conda” and “Docker” respectively (as at 30th May 2023). Eventually, it’s also worth mentionning that the Guix project uses Software Heritage as a fallback system to provide a package source code if the download of the source code from its original location failed.

**Comment by markziemann** [comment]
45. Vallet N, Michonneau D, Tournier S. Toward practical transparent verifiable and long-term reproducible research using guix. Sci. Data 2022; 9:597

54. Courtès L. Reproducibility and performance: Why choose? 2022;
55. Volunteers GP. GNU guix reference manual. 2022;
56. Wurmus R, Uyar B, Osberg B, et al. PiGx: Reproducible genomics analysis pipelines with GNU guix. Gigascience 2018; 7:
 57. Perkel JM. Challenge to scientists: Does your ten-year-old code still run? Nature 2020; 584:656–658

**Comment by pierrepo** [comment]
Awesome!
